import { ModelInfo } from "@shared/api"

function calculateApiCostInternal(
	modelInfo: ModelInfo,
	inputTokens: number, // Note: For OpenAI-style, this is non-cached tokens. For Anthropic-style, this is total input tokens.
	outputTokens: number,
	cacheCreationInputTokens: number,
	cacheReadInputTokens: number,
	totalInputTokensForPricing?: number, // The *total* input tokens, used for tiered pricing lookup
	thinkingBudgetTokens?: number, // Add thinking budget info
): number {
	const usedThinkingBudget = thinkingBudgetTokens && thinkingBudgetTokens > 0

	// Default prices
	let effectiveInputPrice = modelInfo.inputPrice || 0
	let effectiveOutputPrice = modelInfo.outputPrice || 0
	let effectiveCacheReadsPrice = modelInfo.cacheReadsPrice || 0
	let effectiveCacheWritesPrice = modelInfo.cacheWritesPrice || 0

	// Handle tiered pricing if available
	if (modelInfo.tiers && modelInfo.tiers.length > 0 && totalInputTokensForPricing !== undefined) {
		// Ensure tiers are sorted by contextWindow ascending before finding
		const sortedTiers = [...modelInfo.tiers].sort((a, b) => a.contextWindow - b.contextWindow)

		// Find the first tier where the total input tokens are less than or equal to the limit
		const tier = sortedTiers.find((t) => totalInputTokensForPricing <= t.contextWindow)

		if (tier) {
			// Apply all tiered price values if they exist
			effectiveInputPrice = tier.inputPrice ?? effectiveInputPrice
			effectiveOutputPrice = tier.outputPrice ?? effectiveOutputPrice
			effectiveCacheReadsPrice = tier.cacheReadsPrice ?? effectiveCacheReadsPrice
			effectiveCacheWritesPrice = tier.cacheWritesPrice ?? effectiveCacheWritesPrice
		} else {
			// Should ideally not happen if Infinity is used for the last tier, but fallback just in case
			const lastTier = sortedTiers[sortedTiers.length - 1]
			if (lastTier) {
				effectiveInputPrice = lastTier.inputPrice ?? effectiveInputPrice
				effectiveOutputPrice = lastTier.outputPrice ?? effectiveOutputPrice
				effectiveCacheReadsPrice = lastTier.cacheReadsPrice ?? effectiveCacheReadsPrice
				effectiveCacheWritesPrice = lastTier.cacheWritesPrice ?? effectiveCacheWritesPrice
			}
		}
	}

	// Override output price for thinking mode if applicable
	if (usedThinkingBudget && modelInfo.thinkingConfig?.outputPrice !== undefined) {
		effectiveOutputPrice = modelInfo.thinkingConfig.outputPrice
		// TODO: Add support for tiered thinking budget output pricing if needed in the future
	}

	const cacheWritesCost = (effectiveCacheWritesPrice / 1_000_000) * cacheCreationInputTokens
	const cacheReadsCost = (effectiveCacheReadsPrice / 1_000_000) * cacheReadInputTokens

	// Use effectiveInputPrice for baseInputCost. Note: 'inputTokens' here is the potentially adjusted count (e.g., non-cached for OpenAI)
	const baseInputCost = (effectiveInputPrice / 1_000_000) * inputTokens

	// Use effectiveOutputPrice for outputCost
	const outputCost = (effectiveOutputPrice / 1_000_000) * outputTokens

	const totalCost = cacheWritesCost + cacheReadsCost + baseInputCost + outputCost
	return totalCost
}

/**
 * Calculates the total API cost for an Anthropic-style usage response.
 *
 * In the Anthropic token-counting convention, `inputTokens` represents only the
 * **non-cached** portion of the prompt — cached tokens are reported separately via
 * `cacheCreationInputTokens` and `cacheReadInputTokens`. The total token count used
 * for tiered-pricing lookup is derived by summing all three values internally.
 *
 * @param modelInfo - Model configuration including price-per-million-token rates and
 *   optional tiered-pricing tiers.
 * @param inputTokens - Non-cached input tokens (as reported by the Anthropic API).
 * @param outputTokens - Output/completion tokens generated by the model.
 * @param cacheCreationInputTokens - Tokens written to the prompt cache this turn (optional).
 * @param cacheReadInputTokens - Tokens read from the prompt cache this turn (optional).
 * @param thinkingBudgetTokens - Extended thinking budget tokens, if thinking mode was
 *   enabled. When non-zero, the model's `thinkingConfig.outputPrice` is used instead
 *   of the standard output price.
 * @returns Total cost in USD.
 */
// For Anthropic compliant usage, the input tokens count does NOT include the cached tokens
export function calculateApiCostAnthropic(
	modelInfo: ModelInfo,
	inputTokens: number,
	outputTokens: number,
	cacheCreationInputTokens?: number,
	cacheReadInputTokens?: number,
	thinkingBudgetTokens?: number,
): number {
	const cacheCreationInputTokensNum = cacheCreationInputTokens || 0
	const cacheReadInputTokensNum = cacheReadInputTokens || 0
	// Anthropic style: inputTokens already represents the total, so pass it directly for tiered pricing lookup if needed
	// (though Anthropic models currently don't use tiered pricing based on input size)
	// Anthropic style doesn't need totalInputTokensForPricing as its inputTokens already represents the total
	return calculateApiCostInternal(
		modelInfo,
		inputTokens,
		outputTokens,
		cacheCreationInputTokensNum,
		cacheReadInputTokensNum,
		inputTokens + cacheCreationInputTokensNum + cacheReadInputTokensNum, // used for tiered price lookup
		thinkingBudgetTokens,
	)
}

/**
 * Calculates the total API cost for an OpenAI-style usage response.
 *
 * In the OpenAI token-counting convention, `inputTokens` is the **total** prompt token
 * count and already includes any cached tokens. This function derives the non-cached
 * portion by subtracting cache hits before computing the base input cost, ensuring
 * cached tokens are not double-billed at the full input price.
 *
 * @param modelInfo - Model configuration including price-per-million-token rates and
 *   optional tiered-pricing tiers.
 * @param inputTokens - Total input tokens including cached tokens (as reported by the
 *   OpenAI API's `prompt_tokens` field).
 * @param outputTokens - Output/completion tokens generated by the model.
 * @param cacheCreationInputTokens - Tokens written to the prompt cache this turn (optional).
 * @param cacheReadInputTokens - Tokens read from the prompt cache this turn (optional).
 * @param thinkingBudgetTokens - Extended thinking budget tokens, if thinking mode was
 *   enabled. When non-zero, the model's `thinkingConfig.outputPrice` is used instead
 *   of the standard output price.
 * @returns Total cost in USD.
 */
// For OpenAI compliant usage, the input tokens count INCLUDES the cached tokens
export function calculateApiCostOpenAI(
	modelInfo: ModelInfo,
	inputTokens: number, // For OpenAI-style, this includes cached tokens
	outputTokens: number,
	cacheCreationInputTokens?: number,
	cacheReadInputTokens?: number,
	thinkingBudgetTokens?: number, // Pass thinking budget info
): number {
	const cacheCreationInputTokensNum = cacheCreationInputTokens || 0
	const cacheReadInputTokensNum = cacheReadInputTokens || 0
	// Calculate non-cached tokens for the internal function's 'inputTokens' parameter
	const nonCachedInputTokens = Math.max(0, inputTokens - cacheCreationInputTokensNum - cacheReadInputTokensNum)
	// Pass the original 'inputTokens' as 'totalInputTokensForPricing' for tier lookup
	return calculateApiCostInternal(
		modelInfo,
		nonCachedInputTokens,
		outputTokens,
		cacheCreationInputTokensNum,
		cacheReadInputTokensNum,
		inputTokens,
		thinkingBudgetTokens,
	)
}

/**
 * Calculates the total API cost for a Qwen-style usage response.
 *
 * Qwen follows the same token-counting convention as OpenAI: `inputTokens` is the
 * **total** prompt token count and includes cached tokens. This function behaves
 * identically to {@link calculateApiCostOpenAI} and exists as a named alias so that
 * call-sites explicitly communicate which provider's response format they are handling.
 *
 * @param modelInfo - Model configuration including price-per-million-token rates and
 *   optional tiered-pricing tiers.
 * @param inputTokens - Total input tokens including cached tokens (as reported by
 *   Qwen's usage response).
 * @param outputTokens - Output/completion tokens generated by the model.
 * @param cacheCreationInputTokens - Tokens written to the prompt cache this turn (optional).
 * @param cacheReadInputTokens - Tokens read from the prompt cache this turn (optional).
 * @param thinkingBudgetTokens - Extended thinking budget tokens, if thinking mode was
 *   enabled. When non-zero, the model's `thinkingConfig.outputPrice` is used instead
 *   of the standard output price.
 * @returns Total cost in USD.
 */
// For Qwen compliant usage, follows OpenAI-style token counting where input tokens include cached tokens
export function calculateApiCostQwen(
	modelInfo: ModelInfo,
	inputTokens: number, // For Qwen-style, this includes cached tokens
	outputTokens: number,
	cacheCreationInputTokens?: number,
	cacheReadInputTokens?: number,
	thinkingBudgetTokens?: number,
): number {
	const cacheCreationInputTokensNum = cacheCreationInputTokens || 0
	const cacheReadInputTokensNum = cacheReadInputTokens || 0
	// Calculate non-cached tokens for the internal function's 'inputTokens' parameter
	const nonCachedInputTokens = Math.max(0, inputTokens - cacheCreationInputTokensNum - cacheReadInputTokensNum)
	// Pass the original 'inputTokens' as 'totalInputTokensForPricing' for tier lookup
	return calculateApiCostInternal(
		modelInfo,
		nonCachedInputTokens,
		outputTokens,
		cacheCreationInputTokensNum,
		cacheReadInputTokensNum,
		inputTokens,
		thinkingBudgetTokens,
	)
}
